---
title: "Fitting state-space models using the R package TMB"
author: "Marie Auger-Methe"
date: "28/02/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Info

This tutorial is heavily based on Appendix S1 (Supporting Information) from Auger-Méthé, M., Newman, K., Cole, D., Empacher, F., Gryba, R., King, A. A., Leos-Barajas, V., Mills Flemming, J., Nielsen, A., Petris, G., and Thomas, L.. 2021. A guide to state–space modeling of ecological time series. Ecological Monographs 91(4):e01470. 10.1002/ecm.1470 (Open access,  https://doi.org/10.1002/ecm.1470). Please refer to the paper and tutorial for more in-depth information on state-space models and how to apply them to data using R.

## Introducing the method with a simple univariate linear Gaussian state-space models

We start by exploring a very simple SSM: a simple linear SSM with Normal distributions. This model is not linked to an ecological example; it's just a teaching tool. This linear Gaussian SSM
consists of two equations for two time series.

The process equation (or state equation) is:
\begin{equation}
  z_t = \beta z_{t-1} + \epsilon_t, \;\;\; \epsilon_t \sim \text{N}(0, \sigma_p^2),
  \label{E.toy4p.p}
\end{equation}
where $z_t$ is the state value at time $t$, for $t=1, ..., T$ and $\beta$ represents the autocorrelation in the state values. The states are generally unknown, i.e., cannot be observed directly, and are sometimes referred to as latent states or hidden states. This equation represents the evolution of the hidden state as a correlated random walk. The equation implies that there is some stochasticity in the process. This stochasticity is often referred as process variation and is here described by a Normal (Gaussian) distribution with standard deviation $\sigma_p$. For simplicity, we set the initial state value to be 0, i.e., $z_0 =0$.

The observation equation (or measurement equation) is:
\begin{equation}
  y_t = \alpha z_{t} + \eta_t, \;\;\; \eta_t \sim \text{N}(0, \sigma_o^2),
  \label{E.toy4p.o}
\end{equation}
where $y_t$ is the observation at time $t$, for $t=1, ..., T$ and $\alpha$ is a constant of proportionality that represents any systematic discrepancy between the observations and the states (e.g., the average detection rate). This equation links the observation at time $t$ to the underlying state at that time. The equation implies that we are observing the process with error. This error term is often referred as the observation error and, here, is described by a Normal distribution with standard deviation $\sigma_o$.

This model has four parameters: $\alpha, \beta, \sigma_o, \sigma_p$. It is sometimes
difficult to accurately estimate all four parameters, something we will demonstrate in the sections below. It is useful to explore a simpler model, where we fix two of the parameters and only have two parameters to estimate. In the simpler model, we fix both $\alpha$ and $\beta$ to 1, resulting in the following.

The process equation is now:
\begin{equation}
  z_t = z_{t-1} + \epsilon_t, \;\;\; \epsilon_t \sim \text{N}(0, \sigma_p^2),
  \label{E.toy2p.p} 
\end{equation}
and represents the evolution of the hidden state as a simple random walk. The observation equation is now:
\begin{equation}
  y_t = z_{t} + \eta_t, \;\;\; \eta_t \sim \text{N}(0, \sigma_o^2),
  \label{E.toy2p.o}
\end{equation}
where we assume that there is no systematic bias in the observation (i.e. we observed the state with some error but the observations are not systematically smaller or larger than the states).
